### ISSUE TITLE
Improve usability for new users

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#60]
### Story
As a new plugin user, I want it to be easier to get and add my API keys to the plugin, so that I can add my API keys quickly and get started using the plugin.

### Acceptance Criteria

- Given I am a new user who has never used the plugin before, when I open the plugin for the first time, then I am presented information/links that helps me create and add and API key to the plugin
- Given I have created an API key, then I am presented with a list of data that I can start to use
- Given I am a new user who has never used a Koordinates service before, then I am presented information on how to create a Koordinates account
- Given I am a new user who has never used the plugin before, when I have obtained my API key, it is simple for me to add it to the plugin settings

### Tasks
- [x] Move help information from the 'about' page to a 'help' page
- [ ] Restructure and rewrite the 'help' page to make it more user friendly and get to the important info earlier
- [ ] Add direct links to API key pages, e.g. https://data.linz.govt.nz/my/api/ and https://basemaps.linz.govt.nz 
- [ ] Add info on how to create a Kx account (is this needed?)
- [ ] Remove external links where possible (e.g. list of services)
- [x] Default to the settings page if plugin is opened with no API keys saved
- [x] If no API keys have been added then add a user friendly message that explains what the user needs to do to add an API key
- [x] Remove the 'blank' option for the dropdown for API keys
- [x] Reorder the dropdown of domains to: LDS, Basemaps and then others in alphabetical order
- [x] Remove the UI freeze message from settings screen (no longer relevant)
- [x] Add a message to the settings screen linking to the help screen to find out how to get an API key

**Comment by billgeo** [comment]
FYI @vlindsay

**Comment by billgeo** [comment]
@vlindsay is this still something that in the plans?
